name = "majorai-email-sender"
main = "workers/email-sender.js"
compatibility_date = "2026-06-11"
workers_dev = true

[[send_email]]
name = "EMAIL"

[vars]
AUTH_EMAIL_FROM = "login@ailatest.org"
AUTH_EMAIL_FROM_NAME = "majorAI"
